version: '3.9'

networks:
  intranet:
    external: true

services:
  traefik:
    image: traefik
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.intranet.address=:80"
    restart: always
    ports:
      - "80:80"
      - "8080:8080" # The Web UI (enabled by --api)
    networks:
      intranet:
        aliases:
          - gateway.gmaintweb
          - equipment.gmaintweb
          - maintenance.gmaintweb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
